language: php

matrix:
  include:
    - php: 5.4
      env: DEPENDENCIES='low'
    - php: 5.4
    - php: 5.5
    - php: 5.6
  allow_failures:
    - env: DEPENDENCIES='low'

services: mongodb

before_install:
  - composer self-update
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - ./bin/phpspec run --format=pretty
