build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\isolate\doctrine-bridge

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
    
install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - cd c:\projects\isolate\doctrine-bridge
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist --no-progress --ansi --ignore-platform-reqs

test_script:
  - cd c:\projects\isolate\doctrine-bridge
  - bin\phpspec run --format=dot --ansi 
